# Site settings
title: "Machine-learning for Communication Blog"
email: tomerraviv95@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A blog dedicated to machine learning for wireless communications, focusing on model-based approaches which are the interest of my PhD. I may add some additional unrelated content :)"
title_image: "https://i.imgur.com/z5gX2Lr.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/tomerraviv95/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
# youtube_username: Model-Based for Communication
github_username:  tomerraviv95
# instagram_username: 
# reddit_username: 
linkedin_link: www.linkedin.com/in/tomer-raviv-ds/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# xing_link:
# facebook_link:
google_scholar_username: X-LB01UAAAAJ&hl

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
